// Standard GST Unit Quantity Codes (UQCs) mapping
export const UQC_MAP: Record<string, string> = {
  pcs: 'PCS',
  piece: 'PCS',
  pieces: 'PCS',
  nos: 'NOS',
  number: 'NOS',
  numbers: 'NOS',
  box: 'BOX',
  boxes: 'BOX',
  ctn: 'CTN',
  carton: 'CTN',
  cartons: 'CTN',
  pack: 'PAC',
  pac: 'PAC',
  packet: 'PAC',
  packets: 'PAC',
  kg: 'KGS',
  kgs: 'KGS',
  kilogram: 'KGS',
  kilograms: 'KGS',
  gm: 'GMS',
  gms: 'GMS',
  gram: 'GMS',
  grams: 'GMS',
  ltr: 'LTR',
  litre: 'LTR',
  litres: 'LTR',
  liter: 'LTR',
  liters: 'LTR',
  ml: 'MLT',
  millilitre: 'MLT',
  meter: 'MTR',
  metre: 'MTR',
  meters: 'MTR',
  mtr: 'MTR',
  sqm: 'SQM',
  sqf: 'SQF',
  sqft: 'SQF',
  bottle: 'BTL',
  bottles: 'BTL',
  btl: 'BTL',
  can: 'CAN',
  cans: 'CAN',
  bag: 'BAG',
  bags: 'BAG',
  tin: 'TIN',
  tins: 'TIN',
  jar: 'JAR',
  jars: 'JAR',
  doz: 'DOZ',
  dozen: 'DOZ',
  set: 'SET',
  sets: 'SET',
  roll: 'ROL',
  rolls: 'ROL',
  bundle: 'BDL',
  bundles: 'BDL',
  drum: 'DRM',
  drums: 'DRM',
  tube: 'TUB',
  tubes: 'TUB',
  pair: 'PRS',
  pairs: 'PRS',
  oth: 'OTH',
  other: 'OTH',
};

export function toUQC(unitName: string): string {
  if (!unitName) return 'OTH';
  const clean = String(unitName).trim().toLowerCase();
  return UQC_MAP[clean] || 'OTH';
}
